export const bankCategories = [
  { name: "eximMDL", currency: "MDL", label: "EXIM MDL" },
  { name: "eximEUR", currency: "EUR", label: "EXIM EUR" },
  { name: "eximUSD", currency: "USD", label: "EXIM USD" },
  { name: "energMDL", currency: "MDL", label: "ENERG MDL" },
  { name: "energEUR", currency: "EUR", label: "ENERG EUR" },
  { name: "maibEUR", currency: "EUR", label: "MAIB EUR" },
  { name: "maibUSD", currency: "USD", label: "MAIB USD" },
  { name: "vbEUR", currency: "EUR", label: "VB EUR" },
  { name: "vbUSD", currency: "USD", label: "VB USD" },
  { name: "micbEUR", currency: "EUR", label: "MICB EUR" },
  { name: "micbMDL", currency: "MDL", label: "MICB MDL" },
  { name: "otpEUR", currency: "EUR", label: "OTP EUR" },
  { name: "domEUR", currency: "EUR", label: "ДОМ EUR" },
  { name: "domMDL", currency: "MDL", label: "ДОМ MDL" },
  { name: "domUSD", currency: "USD", label: "ДОМ USD" },
  { name: "debitEUR", currency: "EUR", label: "DEBIT EUR" },
  { name: "creditUSD", currency: "EUR", label: "CREDIT EUR" },
] as const;
